---
- name: Centreon API authentication
  hosts: testing-machine
  vars_files:
    - url.yml
    - creds2.yml
  tasks:
    - name: Authentication
      uri:
         method: POST
         url: "{{ centreon_auth_url }}"
         body: "username={{ centreon_user }}&password={{ centreon_password }}"
         follow_redirects: true
      register: login
      delegate_to: localhost

    - set_fact:
        auth_token: "{{ login.json.authToken }}"

    - debug:
        var: auth_token

    - name: Add host to Centreon configuration
      uri:
        method: POST
        headers:
          Content-Type: "application/json"
          centreon-auth-token: "{{ auth_token }}"
        url: "{{ centreon_api_url }}"
        body_format: json
        body:
          action: "add"
          object: "host"
          values: "{{ item }};{{ item }};{{ hostvars[item]['ansible_host'] }};custom-linux-server-verso;central;linux-servers"
      delegate_to: localhost
      loop: "{{ groups['testing-machine'] }}"

    - name: Add Current Users service
      uri:
        method: POST
        headers: 
          Content-Type: "application/json"
          centreon-auth-token: "{{ auth_token }}"
        url: "{{ centreon_api_url }}"
        body_format: json        
        body:
          action: "add"
          object: "service"
          values: "{{ inventory_hostname }};Current Users;Linux - Users"
      delegate_to: localhost
      
    - name: Add Load Avarage service
      uri:
        method: POST
        headers:
          Content-Type: "application/json"
          centreon-auth-token: "{{ auth_token }}"
        url: "{{ centreon_api_url }}"
        body_format: json
        body:
          action: "add"
          object: "service"
          values: "{{ inventory_hostname }};Load Avarage;Linux - Load Avarage"
      delegate_to: localhost

    - name: Add PING service
      uri:
        method: POST
        headers: 
          Content-Type: "application/json"
          centreon-auth-token: "{{ auth_token }}"
        url: "{{ centreon_api_url }}"
        body_format: json
        body:
          action: "add"
          object: "service"
          values: "{{ inventory_hostname  }};PING;Base-Ping-LAN-custom"
      delegate_to: localhost

    - name: Add Swap Usage service
      uri:
       method: POST
       headers:
         Content-Type: "application/json"
         centreon-auth-token: "{{ auth_token }}"
       url: "{{ centreon_api_url }}"
       body_format: json
       body:
         action: "add"
         object: "service"
         values: "{{ inventory_hostname }};Swap Usage;Linux - Swap Usage"
      delegate_to: localhost

    - name: Add Total Processes service
      uri:
       method: POST
       headers:
         Content-Type: "application/json"
         centreon-auth-token: "{{ auth_token }}"
       url: "{{ centreon_api_url }}"
       body_format: json
       body:
         action: "add"
         object: "service"
         values: "{{ inventory_hostname }};Total Processes;Linux - Total Processes"
      delegate_to: localhost

    - name: Add Zombie Processes service
      uri:
       method: POST
       headers:
         Content-Type: "application/json"
         centreon-auth-token: "{{ auth_token }}"
       url: "{{ centreon_api_url }}"
       body_format: json
       body:
         action: "add"
         object: "service"
         values: "{{ inventory_hostname }};Zombie Processes;Linux - Zombie Processes"
      delegate_to: localhost

    - name: Add Partition services
      uri:
       method: POST
       headers:
         Content-Type: "application/json"
         centreon-auth-token: "{{ auth_token }}"
       url: "{{ centreon_api_url }}"
       body_format: json
       body:
         action: "add"
         object: "service"
         values: "{{ inventory_hostname }};Part. {{ item.mount }};Linux - Part. {{ item.mount }}"
      delegate_to: localhost
      with_items:
        - "{{ ansible_mounts }}"
