---
- name: Copy SSH key to remote hosts
  hosts: testing-machine
  gather_facts: no

  tasks:
    - name: Ensure SSH key exists
      stat:
        path: /root/.ssh/id_rsa.pub
      register: ssh_key
      delegate_to: localhost

    - name: Copy SSH key to remote hosts
      command: sshpass -p "{{ ansible_ssh_pass }}" ssh-copy-id -i /root/.ssh/id_rsa.pub {{ ansible_user }}@{{ inventory_hostname }}
      when: ssh_key.stat.exists
      delegate_to: localhost

- name: Installation of NRPE and Centreon enrollment
  hosts: testing-machine
  become: yes
  tasks:
    - name: Installing EPEL RPM
      command: dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
      register: epel_output
      changed_when: epel_output.rc != 0

    - name: Installing NRPE
      command: dnf install nagios-plugins-disk nagios-plugins-load nagios-plugins-procs nagios-plugins-swap nagios-plugins-users nrpe -y
      register: nrpe_output
      changed_when: nrpe_output.rc != 0

    - name: Copying configuration file
      copy: 
         src: /root/nrpe.cfg
         dest: /etc/nagios/nrpe.cfg
         mode: '0644'

    - name: Enabling NRPE service
      systemd:
         name: nrpe
         enabled: yes
         state: started
      
    - name: Authentication
      uri:
         method: POST
         url: "{{ centreon_auth_url }}"
         body: "username={{ centreon_user }}&password={{ centreon_password }}"
      register: login
      delegate_to: localhost

    - name: Setting authentication token
      set_fact:
        auth_token: "{{ login.json.authToken }}"

    - name: Add host to Centreon configuration
      uri:
        method: POST
        headers:
          Content-Type: "application/json"
          centreon-auth-token: "{{ auth_token }}"
        url: "{{ centreon_api_url }}"
        body_format: json
        body:
          action: "add"
          object: "host"
          values: "{{ item }};{{ item }};{{ hostvars[item]['ansible_host'] }};custom-linux-server-verso;central;linux-servers"
      delegate_to: localhost
      loop: "{{ groups['testing-machine'] }}"

    - name: Add Current Users service
      uri:
        method: POST
        headers: 
          Content-Type: "application/json"
          centreon-auth-token: "{{ auth_token }}"
        url: "{{ centreon_api_url }}"
        body_format: json        
        body:
          action: "add"
          object: "service"
          values: "{{ inventory_hostname }};Current Users;Linux - Users"
      delegate_to: localhost
      
    - name: Add Load Avarage service
      uri:
        method: POST
        headers:
          Content-Type: "application/json"
          centreon-auth-token: "{{ auth_token }}"
        url: "{{ centreon_api_url }}"
        body_format: json
        body:
          action: "add"
          object: "service"
          values: "{{ inventory_hostname }};Load Avarage;Linux - Load Avarage"
      delegate_to: localhost

    - name: Add PING service
      uri:
        method: POST
        headers: 
          Content-Type: "application/json"
          centreon-auth-token: "{{ auth_token }}"
        url: "{{ centreon_api_url }}"
        body_format: json
        body:
          action: "add"
          object: "service"
          values: "{{ inventory_hostname  }};PING;Base-Ping-LAN-custom"
      delegate_to: localhost

    - name: Add Swap Usage service
      uri:
       method: POST
       headers:
         Content-Type: "application/json"
         centreon-auth-token: "{{ auth_token }}"
       url: "{{ centreon_api_url }}"
       body_format: json
       body:
         action: "add"
         object: "service"
         values: "{{ inventory_hostname }};Swap Usage;Linux - Swap Usage"
      delegate_to: localhost

    - name: Add Total Processes service
      uri:
       method: POST
       headers:
         Content-Type: "application/json"
         centreon-auth-token: "{{ auth_token }}"
       url: "{{ centreon_api_url }}"
       body_format: json
       body:
         action: "add"
         object: "service"
         values: "{{ inventory_hostname }};Total Processes;Linux - Total Processes"
      delegate_to: localhost

    - name: Add Zombie Processes service
      uri:
       method: POST
       headers:
         Content-Type: "application/json"
         centreon-auth-token: "{{ auth_token }}"
       url: "{{ centreon_api_url }}"
       body_format: json
       body:
         action: "add"
         object: "service"
         values: "{{ inventory_hostname }};Zombie Processes;Linux - Zombie Processes"
      delegate_to: localhost

    - name: Add Partition services
      uri:
       method: POST
       headers:
         Content-Type: "application/json"
         centreon-auth-token: "{{ auth_token }}"
       url: "{{ centreon_api_url }}"
       body_format: json
       body:
         action: "add"
         object: "service"
         values: "{{ inventory_hostname }};Part. {{ item.mount }};Linux - Part. {{ item.mount }}"
      delegate_to: localhost
      with_items:
        - "{{ ansible_mounts }}"

    - name: Apply configuration to Centreon
      command: "centreon -u {{ centreon_user }} -p {{ centreon_password }} -a APPLYCFG -v 1"
      delegate_to: lxp-centreon19.srv-lx.vag.local
      register: applyconf_output
      changed_when: applyconf_output.rc != 0

    - name: Print poller messages
      debug:
        msg: "{{ applyconf_output.stdout_lines }}"
