---
- name: Copy SSH key to remote hosts
  hosts: all
  gather_facts: no

  tasks:
    - name: Ensure SSH key exists
      stat:
        path: ~/.ssh/id_rsa.pub
      register: ssh_key

    - name: Copy SSH key to remote hosts
      become: yes
      shell: /usr/bin/sshpass -p "{{ ansible_ssh_pass }}" ssh-copy-id root@{{ inventory_hostname }}
