- name: Run Python script from GitHub
  hosts: your_hosts  # Replace with your actual hosts
  tasks:
    - name: Download the Python script
      get_url:
        url: 'https://github.com/dvolic21/semaphore-test/blob/main/testing.py'
        dest: '/ansible_tmp/testing.py'

    - name: Run the Python script
      command: python /ansible_tmp/testing.py
      register: script_output

    - name: Display the output
      debug:
        msg: "{{ script_output.stdout }}"
