- name: Run Python script from GitHub
  hosts: localhost
  tasks:
    - name: Download the Python script
      get_url:
        url: https://raw.githubusercontent.com/dvolic21/semaphore-test/main/testing.py
        dest: '~/ansible_tmp/testing.py'
 
    - name: Run the Python script
      command: python ~/ansible_tmp/testing.py
      register: script_output
 
    - name: Display the output
      debug:
        msg: "{{ script_output.stdout |  ansible.builtin.to_json }}"
