- name: Run Python script from GitHub
  hosts: your_hosts  # Replace with your actual hosts
  tasks:
    - name: Display current local_tmp setting
      debug:
        msg: "Current local_tmp is set to: {{ ansible_env.ANSIBLE_LOCAL_TMP | default('not set') }}"

    - name: Download the Python script
      get_url:
        url: 'https://raw.githubusercontent.com/dvolic21/semaphore-test/main/testing.py'
        dest: '/ansible_tmp/testing.py'  # Path to save the script on the target host

    - name: Run the Python script
      command: python /ansible_tmp/testing.py  # Adjust to python3 if necessary
      register: script_output

    - name: Display the output
      debug:
        msg: "{{ script_output.stdout }}"
